Bug Fixes:     - After backup finishes, send an alert, even though the UI has       disconnected from the telnet connection.
    - Fixed exception:
        TypeError: not all arguments converted during string formatting
     caused by text messages split into multiple lines incorrectly.